import { ArrowRight, Eye, HeartHandshake, ScanText, ShieldCheck, Sparkles } from "lucide-react";
import PublicShell from "@/components/PublicShell";

const principles = [
  { icon: Eye, number: "01", title: "Show the signal", copy: "A probability without context is just a scary number. Dicript surfaces the patterns underneath so writers can make informed decisions." },
  { icon: ShieldCheck, number: "02", title: "Protect the work", copy: "Your drafts belong to you. We keep privacy visible, history intentional, and uncertainty honest." },
  { icon: HeartHandshake, number: "03", title: "Keep humans in the loop", copy: "We build tools for better judgment, not automated verdicts. Writing is more than a classification." },
];

export default function About() {
  return <PublicShell eyebrow="About Dicript"><main className="public-main about-main"><section className="about-hero"><div><div className="section-label"><span className="section-dot" />About Dicript</div><h1>Writing tools with a <em>human</em> point of view.</h1><p>Dicript is a small writing intelligence studio helping people understand the patterns in AI-assisted drafts without losing their voice.</p><div className="about-actions"><a className="dark-pill" href="/">Try the detector <ArrowRight /></a><a className="quiet-link" href="/rooms">Explore rooms <ArrowRight /></a></div></div><div className="about-art"><div className="about-grid-lines" /><div className="about-note"><span className="font-mono">FIELD NOTE / 001</span><strong>Better questions make better writing.</strong><small>Dicript is designed to explain, not accuse.</small></div></div></section><section className="about-story"><div><div className="section-label"><span className="section-dot" />The short version</div><h2>AI changed the draft. We wanted to change the conversation.</h2></div><div className="about-story-copy"><p>Most detection tools stop at a percentage. Dicript starts there, then asks what the text is doing: how predictable the rhythm feels, where vocabulary narrows, and which sentences deserve a second look.</p><p>We are building a calm layer between fast tools and thoughtful authorship. That means clear signals, private history, and interfaces that make room for judgment.</p></div></section><section className="principles"><div className="principles-heading"><div className="section-label"><span className="section-dot" />Our principles</div><h2>Useful, legible, human.</h2></div><div className="principle-grid">{principles.map(({ icon: Icon, number, title, copy }) => <article key={number} className="principle-card"><span className="principle-number">{number}</span><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="about-cta"><ScanText /><div><div className="section-label"><span className="section-dot" />Make your next draft clearer</div><h2>Start with a signal, not a verdict.</h2></div><a className="dark-pill" href="/">Open Dicript <ArrowRight /></a></section></main></PublicShell>;
}
