import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Check, ChevronDown, Clipboard, Copy, FileText, History, Info, Layers3, Menu, RotateCcw, ScanText, ShieldCheck, Sparkles, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { analyzeText, sampleText, type DetectionResult, type Confidence } from "@/lib/detection";
import { getSessionId, supabase } from "@/lib/supabase";

type View = "Detector" | "History";
type HistoryItem = { id: string; title: string; ai_probability: number; readability: number; word_count: number; confidence: Confidence; created_at: string };

const profileLabels: Array<{ key: keyof DetectionResult["profile"]; label: string; note: string }> = [
  { key: "predictability", label: "Predictability", note: "How expected the next phrase feels" },
  { key: "uniformity", label: "Sentence uniformity", note: "Similarity in sentence rhythm" },
  { key: "repetition", label: "Phrase repetition", note: "Repeated words and constructions" },
  { key: "variation", label: "Stylistic variation", note: "Range of vocabulary and rhythm" },
];

function Logo() { return <a href="#top" className="flex items-center gap-3" aria-label="Dicript home"><span className="brand-mark"><span /></span><span><strong className="block text-[15px] tracking-[-.04em] text-ink">dicript</strong><small className="block font-mono text-[8px] uppercase tracking-[.18em] text-ink/45">writing intelligence</small></span></a>; }
function SectionLabel({ children }: { children: React.ReactNode }) { return <div className="section-label"><span className="section-dot" />{children}</div>; }
function ScoreDial({ score }: { score: number }) { const radius = 55; const circumference = 2 * Math.PI * radius; const offset = circumference - (score / 100) * circumference; return <div className="score-dial relative h-40 w-40 shrink-0"><svg viewBox="0 0 140 140" className="h-full w-full -rotate-90"><circle cx="70" cy="70" r={radius} fill="none" stroke="rgba(22,22,37,.1)" strokeWidth="8" /><circle cx="70" cy="70" r={radius} fill="none" stroke="url(#scoreGradient)" strokeWidth="8" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={offset} /><defs><linearGradient id="scoreGradient" x1="0" x2="1"><stop stopColor="#ff8b77" /><stop offset="1" stopColor="#baefc8" /></linearGradient></defs></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-[42px] font-semibold leading-none tracking-[-.09em] text-ink">{score}%</span><span className="mt-2 font-mono text-[9px] uppercase tracking-[.16em] text-ink/45">AI-like signals</span></div></div>; }
function ConfidencePill({ value }: { value: Confidence }) { return <span className={`confidence confidence-${value}`}><span className="h-1.5 w-1.5 rounded-full" />Confidence: {value}</span>; }
function SignalBar({ label, value, note }: { label: string; value: number; note: string }) { return <div className="signal-row"><div className="flex items-center justify-between gap-3"><span className="text-[13px] font-medium text-ink/80">{label}</span><span className="font-mono text-[11px] text-ink/50">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink/[.08]"><div className="signal-fill h-full rounded-full" style={{ width: `${value}%` }} /></div><p className="mt-1.5 text-[11px] leading-4 text-ink/45">{note}</p></div>; }

export default function Home() {
  const [view, setView] = useState<View>("Detector");
  const [content, setContent] = useState("");
  const [title, setTitle] = useState("Untitled analysis");
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [expandedSentence, setExpandedSentence] = useState(0);
  const sessionId = useMemo(() => getSessionId(), []);
  const wordCount = useMemo(() => content.trim() ? content.trim().split(/\s+/).length : 0, [content]);

  useEffect(() => { if (!supabase) return; void supabase.from("dicript_analyses").select("id,title,ai_probability,readability,word_count,confidence,created_at").eq("session_id", sessionId).order("created_at", { ascending: false }).limit(12).then(({ data }) => { if (data) setHistory(data as HistoryItem[]); }); }, [sessionId]);

  const persistResult = async (next: DetectionResult) => {
    if (!supabase) return;
    const { data, error } = await supabase.from("dicript_analyses").insert({ session_id: sessionId, title: next.title, content: next.content, word_count: next.wordCount, ai_probability: next.aiProbability, confidence: next.confidence, readability: next.readability, writing_profile: next.profile }).select("id,title,ai_probability,readability,word_count,confidence,created_at").single();
    if (error || !data) { toast.error("The score is ready, but history could not be saved."); return; }
    await supabase.from("dicript_sentences").insert(next.sentences.map((sentence, index) => ({ analysis_id: data.id, sentence_index: index, text: sentence.text, ai_probability: sentence.score, signal: sentence.signal, explanation: sentence.explanation })));
    setHistory((current) => [data as HistoryItem, ...current.filter((item) => item.id !== data.id)].slice(0, 12));
  };

  const runAnalysis = async () => { if (content.trim().length < 40) { toast.error("Add a little more text so Dicript can inspect real writing patterns."); return; } setIsAnalyzing(true); await new Promise((resolve) => setTimeout(resolve, 520)); const next = analyzeText(content, title.trim() || "Untitled analysis"); setResult(next); setExpandedSentence(0); setIsAnalyzing(false); void persistResult(next); };
  const useSample = () => { setTitle("Sample editorial draft"); setContent(sampleText); toast.success("Sample loaded. Run the analysis when you’re ready."); };
  const reset = () => { setContent(""); setTitle("Untitled analysis"); setResult(null); };
  const copyReport = async () => { if (!result) return; await navigator.clipboard?.writeText(`Dicript report\nAI-like signals: ${result.aiProbability}%\nConfidence: ${result.confidence}\nReadability: ${result.readability}/100\nWords analyzed: ${result.wordCount}`); setCopied(true); toast.success("Report copied to clipboard."); window.setTimeout(() => setCopied(false), 1600); };

  return <div id="top" className="min-h-screen bg-paper text-ink"><div className="ambient ambient-coral" /><div className="ambient ambient-mint" /><header className="site-header"><Logo /><nav className={`${mobileNav ? "mobile-open" : ""} site-nav`}><button className={view === "Detector" ? "active" : ""} onClick={() => { setView("Detector"); setMobileNav(false); }}>Detector</button><button className={view === "History" ? "active" : ""} onClick={() => { setView("History"); setMobileNav(false); }}>History <span className="nav-count">{history.length || "0"}</span></button><a href="#methodology" onClick={() => setMobileNav(false)}>Methodology</a><a href="#privacy" onClick={() => setMobileNav(false)}>Privacy</a></nav><div className="header-actions"><span className="desktop-only status-chip"><span />Supabase connected</span><button className="sign-in">Sign in</button><button className="mobile-menu" onClick={() => setMobileNav((open) => !open)} aria-label="Toggle menu">{mobileNav ? <X /> : <Menu />}</button></div></header>
    <main className="mx-auto max-w-[1320px] px-5 pb-20 sm:px-8 lg:px-12"><section className="hero-grid"><div className="hero-copy"><SectionLabel>AI writing intelligence · beta</SectionLabel><h1>Know what your writing <em>signals.</em></h1><p>Dicript helps you understand AI-like patterns, sentence rhythm, and writing quality before anyone else does.</p><div className="hero-proof"><span><Check />Probability, not proof</span><span><ShieldCheck />Your text stays yours</span></div></div><div className="hero-orbit"><div className="orbit-line orbit-line-one" /><div className="orbit-line orbit-line-two" /><div className="hero-card"><div className="flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[.18em] text-ink/45">signal map / 001</span><span className="live-dot"><span />live</span></div><div className="mt-10 flex items-end justify-between gap-5"><div><div className="font-serif text-[54px] leading-none tracking-[-.08em] text-ink">73<span className="text-[24px] text-coral">%</span></div><p className="mt-2 text-xs text-ink/50">AI-like signals</p></div><div className="mini-bars"><span style={{ height: "42%" }} /><span style={{ height: "68%" }} /><span style={{ height: "54%" }} /><span style={{ height: "88%" }} /><span style={{ height: "72%" }} /><span style={{ height: "92%" }} /></div></div><div className="mt-8 border-t border-ink/10 pt-4 text-xs text-ink/55">High predictability detected in 4 of 8 sentences.</div></div></div></section>
    <section className="workspace-shell" aria-label="Dicript analyzer"><div className="workspace-tabs"><button className={view === "Detector" ? "active" : ""} onClick={() => setView("Detector")}><ScanText />Detector</button><button className={view === "History" ? "active" : ""} onClick={() => setView("History")}><History />History <span>{history.length}</span></button><div className="workspace-note"><Info /> Scores are estimates, never proof.</div></div>{view === "History" ? <HistoryView items={history} onOpen={() => { setView("Detector"); toast.info("Open the original text from your Supabase history in the next iteration."); }} /> : <div className="analyzer-grid"><section className="input-panel"><div className="panel-head"><div><SectionLabel>Your text</SectionLabel><h2>Paste your draft</h2></div><span className="word-count">{wordCount.toLocaleString()} / 10,000 words</span></div><input className="title-input" value={title} onChange={(event) => setTitle(event.target.value)} aria-label="Analysis title" placeholder="Name this analysis" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste an essay, article, caption, or paragraph here…" aria-label="Text to analyze" /><div className="input-tools"><button onClick={useSample}><Sparkles />Try a sample</button><button onClick={() => navigator.clipboard?.readText().then((text) => text && setContent(text)).catch(() => toast.error("Clipboard access was not available."))}><Clipboard />Paste here</button><label><Upload />Upload file<input type="file" accept=".txt,.md,.doc,.docx" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setContent(String(reader.result || "")); reader.readAsText(file); }} /></label></div><div className="input-footer"><span>English · Plain text</span><button className="reset-button" onClick={reset}><RotateCcw />Clear</button><button className="analyze-button" onClick={runAnalysis} disabled={isAnalyzing}>{isAnalyzing ? <><span className="spinner" />Reading signals</> : <>Analyze text <ArrowRight /></>}</button></div></section><section className="result-panel">{result ? <ResultView result={result} expandedSentence={expandedSentence} setExpandedSentence={setExpandedSentence} copyReport={copyReport} copied={copied} /> : <EmptyResult />}</section></div>}</section>
    <section id="methodology" className="methodology"><div><SectionLabel>Why Dicript</SectionLabel><h2>More useful than a scary percentage.</h2><p>AI detection is probabilistic. Dicript makes the uncertainty visible, then shows the writing patterns behind the signal.</p></div><div className="method-grid"><div><span>01</span><Layers3 /><h3>Detect</h3><p>See the overall probability and the confidence behind it.</p></div><div><span>02</span><BarChart3 /><h3>Explain</h3><p>Jump from the score to sentence-level signals and reasons.</p></div><div><span>03</span><Sparkles /><h3>Improve</h3><p>Separate writing quality from AI probability so you know what to change.</p></div></div></section><section id="privacy" className="privacy-strip"><ShieldCheck /><div><strong>Your writing is yours.</strong><p>Dicript uses Supabase for your analysis history and does not use submitted text to train models without permission.</p></div><span className="privacy-lock">Private by design</span></section></main><footer className="site-footer"><Logo /><span>Probability is a signal, not a verdict.</span><span>© 2026 Dicript</span></footer></div>;
}

function EmptyResult() { return <div className="empty-result"><div className="empty-orb"><span>∿</span></div><SectionLabel>Detection result</SectionLabel><h2>Your score will appear here.</h2><p>Run an analysis to see AI-like signals, writing profile metrics, and the sentences that shaped the result.</p><div className="empty-chips"><span>Sentence-level</span><span>Explainable</span><span>Private</span></div></div>; }

function ResultView({ result, expandedSentence, setExpandedSentence, copyReport, copied }: { result: DetectionResult; expandedSentence: number; setExpandedSentence: (index: number) => void; copyReport: () => void; copied: boolean }) { return <div className="result-content"><div className="result-summary"><div><SectionLabel>Detection complete</SectionLabel><div className="result-title-row"><h2>{result.aiProbability}% <span>AI-like</span></h2><ConfidencePill value={result.confidence} /></div><p className="result-meta">{result.wordCount.toLocaleString()} words · {result.sentences.length} sentences · just now</p></div><ScoreDial score={result.aiProbability} /></div><div className="result-callout"><Sparkles /><div><strong>Why this result?</strong><p>{result.aiProbability >= 65 ? "Your draft shows consistent sentence structure and predictable transitions in several places." : "Your draft includes a healthy amount of lexical and sentence-level variation."}</p></div><button onClick={() => document.getElementById("sentence-signals")?.scrollIntoView({ behavior: "smooth" })}>Show me examples <ArrowRight /></button></div><div className="profile-card"><div className="profile-head"><div><SectionLabel>Writing profile</SectionLabel><h3>What the text is doing</h3></div><span className="readability-score">Readability <strong>{result.readability}</strong></span></div><div className="profile-grid">{profileLabels.map(({ key, label, note }) => <SignalBar key={key} label={label} value={result.profile[key]} note={note} />)}</div></div><div id="sentence-signals" className="sentence-card"><div className="profile-head"><div><SectionLabel>Sentence intelligence</SectionLabel><h3>Signals in context</h3></div><span className="font-mono text-[10px] uppercase tracking-[.14em] text-ink/40">{result.sentences.length} analyzed</span></div><div className="sentence-list">{result.sentences.map((sentence, index) => <button className={`sentence-item ${sentence.score >= 72 ? "high" : sentence.score >= 50 ? "medium" : "low"} ${expandedSentence === index ? "expanded" : ""}`} key={`${sentence.text}-${index}`} onClick={() => setExpandedSentence(expandedSentence === index ? -1 : index)}><div className="sentence-line"><span className="sentence-index">{String(index + 1).padStart(2, "0")}</span><span className="sentence-text">{sentence.text}</span><span className="sentence-score">{sentence.score}</span><ChevronDown className="sentence-chevron" /></div>{expandedSentence === index && <div className="sentence-detail"><span className="signal-tag">{sentence.signal}</span><p>{sentence.explanation}</p></div>}</button>)}</div></div><button className="copy-report" onClick={copyReport}>{copied ? <Check /> : <Copy />}{copied ? "Copied" : "Copy report"}</button></div>; }

function HistoryView({ items, onOpen }: { items: HistoryItem[]; onOpen: (item: HistoryItem) => void }) { return <div className="history-view"><div className="history-head"><div><SectionLabel>Saved analyses</SectionLabel><h2>Your writing over time.</h2><p>Supabase keeps your signal history ready for comparison.</p></div><button onClick={() => toast.info("Version comparison is coming next.")} className="compare-button">Compare versions <ArrowRight /></button></div>{items.length ? <div className="history-list">{items.map((item) => <button key={item.id} className="history-item" onClick={() => onOpen(item)}><span className="history-icon"><FileText /></span><span className="min-w-0 flex-1 text-left"><strong>{item.title}</strong><small>{new Date(item.created_at).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} · {item.word_count} words</small></span><span className="history-score"><strong>{item.ai_probability}%</strong><small>AI-like</small></span><span className="history-readability">{item.readability}<small>readability</small></span><ArrowRight className="history-arrow" /></button>)}</div> : <div className="history-empty"><History /><h3>No saved analyses yet.</h3><p>Run your first scan and it will appear here.</p></div>}</div>; }
